// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD47WpyESrujD6rxn9NFgoLhUi6ulpEOVI',
    appId: '1:686111372836:android:d789ed81b9a7df0fdc0ab1',
    messagingSenderId: '686111372836',
    projectId: 'chat-project-37100',
    storageBucket: 'chat-project-37100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBdym49sm1acYC7Oaha03grP4K0UW0X7o',
    appId: '1:686111372836:ios:efbd2b0476eb7816dc0ab1',
    messagingSenderId: '686111372836',
    projectId: 'chat-project-37100',
    storageBucket: 'chat-project-37100.appspot.com',
    androidClientId:
        '686111372836-tga9i9du3h499mi9pq3sd2d8a6gnm56d.apps.googleusercontent.com',
    iosClientId:
        '686111372836-okgcmcatle09dvob84tnaus1o8eomajr.apps.googleusercontent.com',
    iosBundleId: 'com.example.appChat',
  );
}
